/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AvailabilityStatus = { 'busy' : null } |
  { 'available' : null } |
  { 'offline' : null };
export type DeliveryType = { 'local' : null } |
  { 'international' : null } |
  { 'state' : null };
export interface Parcel {
  'id' : bigint,
  'weight' : number,
  'status' : Status,
  'deliveryAddress' : string,
  'description' : string,
  'assignedRiderId' : [] | [Principal],
  'deliveryType' : DeliveryType,
  'priceEstimate' : number,
  'pickupAddress' : string,
  'createdTimestamp' : bigint,
  'senderId' : Principal,
}
export interface ParcelInput {
  'weight' : number,
  'deliveryAddress' : string,
  'description' : string,
  'deliveryType' : DeliveryType,
  'pickupAddress' : string,
}
export interface RiderProfile {
  'id' : Principal,
  'status' : AvailabilityStatus,
  'vehicleType' : VehicleType,
  'name' : string,
  'bikeModel' : string,
  'phone' : string,
}
export type Status = { 'assigned' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'inTransit' : null } |
  { 'pickedUp' : null } |
  { 'delivered' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VehicleType = { 'car' : null } |
  { 'van' : null } |
  { 'bike' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRider' : ActorMethod<[bigint, Principal], undefined>,
  'createParcel' : ActorMethod<[ParcelInput], number>,
  'getAllAvailableRiders' : ActorMethod<[], Array<RiderProfile>>,
  'getAllParcels' : ActorMethod<[], Array<Parcel>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyParcels' : ActorMethod<[], Array<Parcel>>,
  'getParcelStatusCounts' : ActorMethod<[], Array<[string, bigint]>>,
  'getRiderParcels' : ActorMethod<[], Array<Parcel>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerRider' : ActorMethod<
    [string, string, string, VehicleType],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateParcelStatus' : ActorMethod<[bigint, Status], undefined>,
  'updateRiderAvailability' : ActorMethod<[AvailabilityStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];