/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DeliveryType = IDL.Variant({
  'local' : IDL.Null,
  'international' : IDL.Null,
  'state' : IDL.Null,
});
export const ParcelInput = IDL.Record({
  'weight' : IDL.Float64,
  'deliveryAddress' : IDL.Text,
  'description' : IDL.Text,
  'deliveryType' : DeliveryType,
  'pickupAddress' : IDL.Text,
});
export const AvailabilityStatus = IDL.Variant({
  'busy' : IDL.Null,
  'available' : IDL.Null,
  'offline' : IDL.Null,
});
export const VehicleType = IDL.Variant({
  'car' : IDL.Null,
  'van' : IDL.Null,
  'bike' : IDL.Null,
});
export const RiderProfile = IDL.Record({
  'id' : IDL.Principal,
  'status' : AvailabilityStatus,
  'vehicleType' : VehicleType,
  'name' : IDL.Text,
  'bikeModel' : IDL.Text,
  'phone' : IDL.Text,
});
export const Status = IDL.Variant({
  'assigned' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'inTransit' : IDL.Null,
  'pickedUp' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Parcel = IDL.Record({
  'id' : IDL.Nat,
  'weight' : IDL.Float64,
  'status' : Status,
  'deliveryAddress' : IDL.Text,
  'description' : IDL.Text,
  'assignedRiderId' : IDL.Opt(IDL.Principal),
  'deliveryType' : DeliveryType,
  'priceEstimate' : IDL.Float64,
  'pickupAddress' : IDL.Text,
  'createdTimestamp' : IDL.Int,
  'senderId' : IDL.Principal,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRider' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'createParcel' : IDL.Func([ParcelInput], [IDL.Float64], []),
  'getAllAvailableRiders' : IDL.Func([], [IDL.Vec(RiderProfile)], ['query']),
  'getAllParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
  'getParcelStatusCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getRiderParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerRider' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, VehicleType],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateParcelStatus' : IDL.Func([IDL.Nat, Status], [], []),
  'updateRiderAvailability' : IDL.Func([AvailabilityStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DeliveryType = IDL.Variant({
    'local' : IDL.Null,
    'international' : IDL.Null,
    'state' : IDL.Null,
  });
  const ParcelInput = IDL.Record({
    'weight' : IDL.Float64,
    'deliveryAddress' : IDL.Text,
    'description' : IDL.Text,
    'deliveryType' : DeliveryType,
    'pickupAddress' : IDL.Text,
  });
  const AvailabilityStatus = IDL.Variant({
    'busy' : IDL.Null,
    'available' : IDL.Null,
    'offline' : IDL.Null,
  });
  const VehicleType = IDL.Variant({
    'car' : IDL.Null,
    'van' : IDL.Null,
    'bike' : IDL.Null,
  });
  const RiderProfile = IDL.Record({
    'id' : IDL.Principal,
    'status' : AvailabilityStatus,
    'vehicleType' : VehicleType,
    'name' : IDL.Text,
    'bikeModel' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Status = IDL.Variant({
    'assigned' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'inTransit' : IDL.Null,
    'pickedUp' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Parcel = IDL.Record({
    'id' : IDL.Nat,
    'weight' : IDL.Float64,
    'status' : Status,
    'deliveryAddress' : IDL.Text,
    'description' : IDL.Text,
    'assignedRiderId' : IDL.Opt(IDL.Principal),
    'deliveryType' : DeliveryType,
    'priceEstimate' : IDL.Float64,
    'pickupAddress' : IDL.Text,
    'createdTimestamp' : IDL.Int,
    'senderId' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRider' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'createParcel' : IDL.Func([ParcelInput], [IDL.Float64], []),
    'getAllAvailableRiders' : IDL.Func([], [IDL.Vec(RiderProfile)], ['query']),
    'getAllParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
    'getParcelStatusCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getRiderParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerRider' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, VehicleType],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateParcelStatus' : IDL.Func([IDL.Nat, Status], [], []),
    'updateRiderAvailability' : IDL.Func([AvailabilityStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };