/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RiderProfile {
    id: Principal;
    status: AvailabilityStatus;
    vehicleType: VehicleType;
    name: string;
    bikeModel: string;
    phone: string;
}
export interface ParcelInput {
    weight: number;
    deliveryAddress: string;
    description: string;
    deliveryType: DeliveryType;
    pickupAddress: string;
}
export interface Parcel {
    id: bigint;
    weight: number;
    status: Status;
    deliveryAddress: string;
    description: string;
    assignedRiderId?: Principal;
    deliveryType: DeliveryType;
    priceEstimate: number;
    pickupAddress: string;
    createdTimestamp: bigint;
    senderId: Principal;
}
export interface UserProfile {
    name: string;
}
export enum AvailabilityStatus {
    busy = "busy",
    available = "available",
    offline = "offline"
}
export enum DeliveryType {
    local = "local",
    international = "international",
    state = "state"
}
export enum Status {
    assigned = "assigned",
    cancelled = "cancelled",
    pending = "pending",
    inTransit = "inTransit",
    pickedUp = "pickedUp",
    delivered = "delivered"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VehicleType {
    car = "car",
    van = "van",
    bike = "bike"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRider(parcelId: bigint, riderId: Principal): Promise<void>;
    createParcel(input: ParcelInput): Promise<number>;
    getAllAvailableRiders(): Promise<Array<RiderProfile>>;
    getAllParcels(): Promise<Array<Parcel>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyParcels(): Promise<Array<Parcel>>;
    getParcelStatusCounts(): Promise<Array<[string, bigint]>>;
    getRiderParcels(): Promise<Array<Parcel>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerRider(name: string, bikeModel: string, phone: string, vehicleType: VehicleType): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateParcelStatus(parcelId: bigint, status: Status): Promise<void>;
    updateRiderAvailability(status: AvailabilityStatus): Promise<void>;
}
import type { AvailabilityStatus as _AvailabilityStatus, DeliveryType as _DeliveryType, Parcel as _Parcel, ParcelInput as _ParcelInput, RiderProfile as _RiderProfile, Status as _Status, UserProfile as _UserProfile, UserRole as _UserRole, VehicleType as _VehicleType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRider(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRider(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRider(arg0, arg1);
            return result;
        }
    }
    async createParcel(arg0: ParcelInput): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.createParcel(to_candid_ParcelInput_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createParcel(to_candid_ParcelInput_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllAvailableRiders(): Promise<Array<RiderProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAvailableRiders();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAvailableRiders();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllParcels(): Promise<Array<Parcel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllParcels();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllParcels();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyParcels(): Promise<Array<Parcel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyParcels();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyParcels();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getParcelStatusCounts(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getParcelStatusCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParcelStatusCounts();
            return result;
        }
    }
    async getRiderParcels(): Promise<Array<Parcel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiderParcels();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiderParcels();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerRider(arg0: string, arg1: string, arg2: string, arg3: VehicleType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerRider(arg0, arg1, arg2, to_candid_VehicleType_n25(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerRider(arg0, arg1, arg2, to_candid_VehicleType_n25(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateParcelStatus(arg0: bigint, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateParcelStatus(arg0, to_candid_Status_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateParcelStatus(arg0, to_candid_Status_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateRiderAvailability(arg0: AvailabilityStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRiderAvailability(to_candid_AvailabilityStatus_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRiderAvailability(to_candid_AvailabilityStatus_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AvailabilityStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvailabilityStatus): AvailabilityStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_DeliveryType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryType): DeliveryType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Parcel_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Parcel): Parcel {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_RiderProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiderProfile): RiderProfile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    weight: number;
    status: _Status;
    deliveryAddress: string;
    description: string;
    assignedRiderId: [] | [Principal];
    deliveryType: _DeliveryType;
    priceEstimate: number;
    pickupAddress: string;
    createdTimestamp: bigint;
    senderId: Principal;
}): {
    id: bigint;
    weight: number;
    status: Status;
    deliveryAddress: string;
    description: string;
    assignedRiderId?: Principal;
    deliveryType: DeliveryType;
    priceEstimate: number;
    pickupAddress: string;
    createdTimestamp: bigint;
    senderId: Principal;
} {
    return {
        id: value.id,
        weight: value.weight,
        status: from_candid_Status_n17(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        description: value.description,
        assignedRiderId: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.assignedRiderId)),
        deliveryType: from_candid_DeliveryType_n20(_uploadFile, _downloadFile, value.deliveryType),
        priceEstimate: value.priceEstimate,
        pickupAddress: value.pickupAddress,
        createdTimestamp: value.createdTimestamp,
        senderId: value.senderId
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    status: _AvailabilityStatus;
    vehicleType: _VehicleType;
    name: string;
    bikeModel: string;
    phone: string;
}): {
    id: Principal;
    status: AvailabilityStatus;
    vehicleType: VehicleType;
    name: string;
    bikeModel: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_AvailabilityStatus_n10(_uploadFile, _downloadFile, value.status),
        vehicleType: from_candid_VehicleType_n12(_uploadFile, _downloadFile, value.vehicleType),
        name: value.name,
        bikeModel: value.bikeModel,
        phone: value.phone
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    busy: null;
} | {
    available: null;
} | {
    offline: null;
}): AvailabilityStatus {
    return "busy" in value ? AvailabilityStatus.busy : "available" in value ? AvailabilityStatus.available : "offline" in value ? AvailabilityStatus.offline : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    car: null;
} | {
    van: null;
} | {
    bike: null;
}): VehicleType {
    return "car" in value ? VehicleType.car : "van" in value ? VehicleType.van : "bike" in value ? VehicleType.bike : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assigned: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    inTransit: null;
} | {
    pickedUp: null;
} | {
    delivered: null;
}): Status {
    return "assigned" in value ? Status.assigned : "cancelled" in value ? Status.cancelled : "pending" in value ? Status.pending : "inTransit" in value ? Status.inTransit : "pickedUp" in value ? Status.pickedUp : "delivered" in value ? Status.delivered : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    local: null;
} | {
    international: null;
} | {
    state: null;
}): DeliveryType {
    return "local" in value ? DeliveryType.local : "international" in value ? DeliveryType.international : "state" in value ? DeliveryType.state : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Parcel>): Array<Parcel> {
    return value.map((x)=>from_candid_Parcel_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RiderProfile>): Array<RiderProfile> {
    return value.map((x)=>from_candid_RiderProfile_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AvailabilityStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvailabilityStatus): _AvailabilityStatus {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_DeliveryType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryType): _DeliveryType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ParcelInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ParcelInput): _ParcelInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: number;
    deliveryAddress: string;
    description: string;
    deliveryType: DeliveryType;
    pickupAddress: string;
}): {
    weight: number;
    deliveryAddress: string;
    description: string;
    deliveryType: _DeliveryType;
    pickupAddress: string;
} {
    return {
        weight: value.weight,
        deliveryAddress: value.deliveryAddress,
        description: value.description,
        deliveryType: to_candid_DeliveryType_n5(_uploadFile, _downloadFile, value.deliveryType),
        pickupAddress: value.pickupAddress
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): {
    car: null;
} | {
    van: null;
} | {
    bike: null;
} {
    return value == VehicleType.car ? {
        car: null
    } : value == VehicleType.van ? {
        van: null
    } : value == VehicleType.bike ? {
        bike: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    assigned: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    inTransit: null;
} | {
    pickedUp: null;
} | {
    delivered: null;
} {
    return value == Status.assigned ? {
        assigned: null
    } : value == Status.cancelled ? {
        cancelled: null
    } : value == Status.pending ? {
        pending: null
    } : value == Status.inTransit ? {
        inTransit: null
    } : value == Status.pickedUp ? {
        pickedUp: null
    } : value == Status.delivered ? {
        delivered: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvailabilityStatus): {
    busy: null;
} | {
    available: null;
} | {
    offline: null;
} {
    return value == AvailabilityStatus.busy ? {
        busy: null
    } : value == AvailabilityStatus.available ? {
        available: null
    } : value == AvailabilityStatus.offline ? {
        offline: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryType): {
    local: null;
} | {
    international: null;
} | {
    state: null;
} {
    return value == DeliveryType.local ? {
        local: null
    } : value == DeliveryType.international ? {
        international: null
    } : value == DeliveryType.state ? {
        state: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
